-- Step 1: Set maintenance flag
INSERT INTO ops.maintenance_flag ("on") VALUES (true);

-- Step 2: Disable triggers
ALTER TABLE public.product_images DISABLE TRIGGER trg_auth_guard;
ALTER TABLE public.products DISABLE TRIGGER trg_auth_guard;
ALTER TABLE public.categories DISABLE TRIGGER trg_auth_guard;
ALTER TABLE public.frame_options DISABLE TRIGGER trg_auth_guard;

-- Step 3: Delete old data
DELETE FROM public.product_images;
DELETE FROM public.frame_options;
DELETE FROM public.products;
DELETE FROM public.categories;

-- Step 4: Insert new categories
INSERT INTO public.categories (slug, name, is_active) VALUES ('historical-frames', '{"en":"Historical Frames","hi":"ऐतिहासिक फ़्रेम"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('led-frames', '{"en":"LED Frames","hi":"LED फ़्रेम"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('led-mirrors', '{"en":"LED Mirrors","hi":"LED मिरर"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('mirrors-insta', '{"en":"Mirrors with Insta Profiles","hi":"इंस्टा प्रोफ़ाइल मिरर"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('anime', '{"en":"Anime","hi":"एनिमे"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('hindu', '{"en":"Hindu","hi":"हिन्दू"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('islamic', '{"en":"Islamic","hi":"इस्लामी"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('christian', '{"en":"Christian","hi":"ईसाई"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('landscapes', '{"en":"Landscapes","hi":"लैंडस्केप"}'::jsonb, true);
INSERT INTO public.categories (slug, name, is_active) VALUES ('calendars', '{"en":"Calendars","hi":"कैलेंडर"}'::jsonb, true);

-- Step 5: Insert products (run after categories are inserted)
-- Get category IDs first: SELECT id, slug FROM public.categories;
-- Then use the actual UUIDs in the INSERT statements below.

-- historical-frames
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('mughal-empire-golden-frame', '{"en":"Mughal Empire Golden Frame","hi":"मुग़ल साम्राज्य गोल्डन फ़्रेम"}'::jsonb, '{"en":"Ornate Mughal-era design with intricate gold leaf patterns and royal arches.","hi":"Ornate Mughal-era design with intricate gold leaf patterns and royal arches."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('rajput-heritage-frame', '{"en":"Rajput Heritage Frame","hi":"राजपूत विरासत फ़्रेम"}'::jsonb, '{"en":"Hand-carved Rajasthani motifs with traditional red and gold color scheme.","hi":"Hand-carved Rajasthani motifs with traditional red and gold color scheme."}'::jsonb, 1199, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('british-colonial-frame', '{"en":"British Colonial Frame","hi":"ब्रिटिश कोलोनियल फ़्रेम"}'::jsonb, '{"en":"Classic Victorian-era style frame with dark walnut finish and brass accents.","hi":"Classic Victorian-era style frame with dark walnut finish and brass accents."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'wood', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('maratha-warrior-frame', '{"en":"Maratha Warrior Frame","hi":"मराठा योद्धा फ़्रेम"}'::jsonb, '{"en":"Bold Maratha design featuring sword motifs and saffron accents.","hi":"Bold Maratha design featuring sword motifs and saffron accents."}'::jsonb, 1149, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('ancient-temple-carving-frame', '{"en":"Ancient Temple Carving Frame","hi":"प्राचीन मंदिर नक्काशी फ़्रेम"}'::jsonb, '{"en":"Inspired by South Indian temple architecture with detailed stone carving patterns.","hi":"Inspired by South Indian temple architecture with detailed stone carving patterns."}'::jsonb, 1399, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('freedom-struggle-tribute-frame', '{"en":"Freedom Struggle Tribute Frame","hi":"स्वतंत्रता संग्राम श्रद्धांजलि फ़्रेम"}'::jsonb, '{"en":"Patriotic design with tricolor accents and Ashoka Chakra motifs.","hi":"Patriotic design with tricolor accents and Ashoka Chakra motifs."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('vintage-portrait-frame', '{"en":"Vintage Portrait Frame","hi":"विंटेज पोर्ट्रेट फ़्रेम"}'::jsonb, '{"en":"Antique-style ornamental frame perfect for heritage photographs.","hi":"Antique-style ornamental frame perfect for heritage photographs."}'::jsonb, 1049, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'wood', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('sikh-guru-heritage-frame', '{"en":"Sikh Guru Heritage Frame","hi":"सिख गुरु विरासत फ़्रेम"}'::jsonb, '{"en":"Respectful design with Khanda symbol and golden border detailing.","hi":"Respectful design with Khanda symbol and golden border detailing."}'::jsonb, 1199, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('buddhist-zen-frame', '{"en":"Buddhist Zen Frame","hi":"बौद्ध ज़ेन फ़्रेम"}'::jsonb, '{"en":"Minimalist frame with lotus motifs and serene earth tones.","hi":"Minimalist frame with lotus motifs and serene earth tones."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'wood', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('medieval-royal-crest-frame', '{"en":"Medieval Royal Crest Frame","hi":"मध्ययुगीन रॉयल क्रेस्ट फ़्रेम"}'::jsonb, '{"en":"European medieval-inspired frame with shield and crown design elements.","hi":"European medieval-inspired frame with shield and crown design elements."}'::jsonb, 1349, (SELECT id FROM public.categories WHERE slug = 'historical-frames'), 'black', false, true);

-- led-frames
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('rgb-color-changing-led-frame', '{"en":"RGB Color Changing LED Frame","hi":"RGB कलर चेंजिंग LED फ़्रेम"}'::jsonb, '{"en":"Remote-controlled RGB LED strip frame with 16 colors and multiple modes.","hi":"Remote-controlled RGB LED strip frame with 16 colors and multiple modes."}'::jsonb, 1999, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('warm-white-led-frame', '{"en":"Warm White LED Frame","hi":"वॉर्म व्हाइट LED फ़्रेम"}'::jsonb, '{"en":"Elegant warm white LED backlight frame for a cozy ambient glow.","hi":"Elegant warm white LED backlight frame for a cozy ambient glow."}'::jsonb, 1599, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('neon-glow-led-frame', '{"en":"Neon Glow LED Frame","hi":"नियॉन ग्लो LED फ़्रेम"}'::jsonb, '{"en":"Vibrant neon-style LED frame perfect for modern rooms and cafes.","hi":"Vibrant neon-style LED frame perfect for modern rooms and cafes."}'::jsonb, 1899, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('music-sync-led-frame', '{"en":"Music Sync LED Frame","hi":"म्यूज़िक सिंक LED फ़्रेम"}'::jsonb, '{"en":"LED frame that pulses and changes with music beats via built-in mic.","hi":"LED frame that pulses and changes with music beats via built-in mic."}'::jsonb, 2499, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('fairy-light-led-frame', '{"en":"Fairy Light LED Frame","hi":"फ़ेयरी लाइट LED फ़्रेम"}'::jsonb, '{"en":"Delicate fairy light LED frame with starry effect for bedrooms.","hi":"Delicate fairy light LED frame with starry effect for bedrooms."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('acrylic-glow-led-frame', '{"en":"Acrylic Glow LED Frame","hi":"एक्रिलिक ग्लो LED फ़्रेम"}'::jsonb, '{"en":"Edge-lit acrylic LED frame with laser-engraved designs that glow.","hi":"Edge-lit acrylic LED frame with laser-engraved designs that glow."}'::jsonb, 1799, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('smart-app-controlled-led-frame', '{"en":"Smart App Controlled LED Frame","hi":"स्मार्ट ऐप LED फ़्रेम"}'::jsonb, '{"en":"WiFi-enabled LED frame controllable via smartphone app with scheduling.","hi":"WiFi-enabled LED frame controllable via smartphone app with scheduling."}'::jsonb, 2999, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('sunset-lamp-led-frame', '{"en":"Sunset Lamp LED Frame","hi":"सनसेट लैंप LED फ़्रेम"}'::jsonb, '{"en":"Trending sunset projection LED frame creating warm gradient light.","hi":"Trending sunset projection LED frame creating warm gradient light."}'::jsonb, 1499, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('dimmable-touch-led-frame', '{"en":"Dimmable Touch LED Frame","hi":"डिमेबल टच LED फ़्रेम"}'::jsonb, '{"en":"Touch-sensitive dimming LED frame with memory function.","hi":"Touch-sensitive dimming LED frame with memory function."}'::jsonb, 1699, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('mirror-backlit-led-frame', '{"en":"Mirror Backlit LED Frame","hi":"मिरर बैकलिट LED फ़्रेम"}'::jsonb, '{"en":"Mirror-finish frame with hidden LED backlight for vanity setups.","hi":"Mirror-finish frame with hidden LED backlight for vanity setups."}'::jsonb, 2199, (SELECT id FROM public.categories WHERE slug = 'led-frames'), 'black', false, true);

-- led-mirrors
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('round-vanity-led-mirror', '{"en":"Round Vanity LED Mirror","hi":"राउंड वैनिटी LED मिरर"}'::jsonb, '{"en":"Hollywood-style round LED mirror with adjustable brightness for makeup.","hi":"Hollywood-style round LED mirror with adjustable brightness for makeup."}'::jsonb, 3499, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('rectangular-bathroom-led-mirror', '{"en":"Rectangular Bathroom LED Mirror","hi":"आयताकार बाथरूम LED मिरर"}'::jsonb, '{"en":"IP44 waterproof LED mirror with anti-fog function and touch switch.","hi":"IP44 waterproof LED mirror with anti-fog function and touch switch."}'::jsonb, 4299, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('full-length-floor-led-mirror', '{"en":"Full Length Floor LED Mirror","hi":"फ़ुल लेंथ फ़्लोर LED मिरर"}'::jsonb, '{"en":"Standing full-length mirror with perimeter LED strip lighting.","hi":"Standing full-length mirror with perimeter LED strip lighting."}'::jsonb, 5999, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('infinity-mirror-led', '{"en":"Infinity LED Mirror","hi":"इन्फ़िनिटी LED मिरर"}'::jsonb, '{"en":"LED infinity mirror creating an endless tunnel illusion effect.","hi":"LED infinity mirror creating an endless tunnel illusion effect."}'::jsonb, 4999, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('smart-touch-dimming-led-mirror', '{"en":"Smart Touch Dimming LED Mirror","hi":"स्मार्ट टच डिमिंग LED मिरर"}'::jsonb, '{"en":"Three-color temperature switching LED mirror with touch controls.","hi":"Three-color temperature switching LED mirror with touch controls."}'::jsonb, 3799, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('oval-ornate-led-mirror', '{"en":"Oval Ornate LED Mirror","hi":"ओवल ऑरनेट LED मिरर"}'::jsonb, '{"en":"Classic oval mirror with decorative frame and warm LED halo.","hi":"Classic oval mirror with decorative frame and warm LED halo."}'::jsonb, 3299, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('frameless-edge-lit-led-mirror', '{"en":"Frameless Edge-Lit LED Mirror","hi":"फ़्रेमलेस LED मिरर"}'::jsonb, '{"en":"Ultra-modern frameless mirror with edge-lit LED technology.","hi":"Ultra-modern frameless mirror with edge-lit LED technology."}'::jsonb, 4499, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('gym-wall-led-mirror', '{"en":"Gym Wall LED Mirror","hi":"जिम वॉल LED मिरर"}'::jsonb, '{"en":"Large wall-mounted LED mirror perfect for home gyms and studios.","hi":"Large wall-mounted LED mirror perfect for home gyms and studios."}'::jsonb, 5499, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('kids-star-led-mirror', '{"en":"Kids Star LED Mirror","hi":"किड्स स्टार LED मिरर"}'::jsonb, '{"en":"Fun star-shaped LED mirror with color-changing modes for children's rooms.","hi":"Fun star-shaped LED mirror with color-changing modes for children's rooms."}'::jsonb, 1999, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('makeup-vanity-table-led-mirror', '{"en":"Makeup Vanity Table LED Mirror","hi":"मेकअप वैनिटी LED मिरर"}'::jsonb, '{"en":"Tabletop LED mirror with 12 Hollywood bulbs and 3 light modes.","hi":"Tabletop LED mirror with 12 Hollywood bulbs and 3 light modes."}'::jsonb, 2999, (SELECT id FROM public.categories WHERE slug = 'led-mirrors'), 'gold', false, true);

-- mirrors-insta
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('instagram-handle-mirror-led', '{"en":"Instagram Handle LED Mirror","hi":"इंस्टाग्राम हैंडल LED मिरर"}'::jsonb, '{"en":"Custom LED mirror shaped as your Instagram handle — perfect for influencers.","hi":"Custom LED mirror shaped as your Instagram handle — perfect for influencers."}'::jsonb, 3999, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('hashtag-neon-mirror', '{"en":"Hashtag Neon Mirror","hi":"हैशटैग नियॉन मिरर"}'::jsonb, '{"en":"Mirror with neon hashtag sign — great for reels and photo backdrops.","hi":"Mirror with neon hashtag sign — great for reels and photo backdrops."}'::jsonb, 2499, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('photo-frame-wall-mirror-set', '{"en":"Photo Frame Wall Mirror Set","hi":"फ़ोटो फ़्रेम वॉल मिरर सेट"}'::jsonb, '{"en":"Set of mirror frames arranged like an Instagram profile grid.","hi":"Set of mirror frames arranged like an Instagram profile grid."}'::jsonb, 3499, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('like-button-mirror', '{"en":"Like Button Mirror","hi":"लाइक बटन मिरर"}'::jsonb, '{"en":"Heart-shaped mirror inspired by the Instagram like button.","hi":"Heart-shaped mirror inspired by the Instagram like button."}'::jsonb, 1499, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('reel-ring-light-mirror', '{"en":"Reels Ring Light Mirror","hi":"रील्स रिंग लाइट मिरर"}'::jsonb, '{"en":"Large mirror with ring light built-in for perfect reel lighting.","hi":"Large mirror with ring light built-in for perfect reel lighting."}'::jsonb, 4499, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('stories-circle-mirror', '{"en":"Stories Circle Mirror","hi":"स्टोरीज़ सर्कल मिरर"}'::jsonb, '{"en":"Circular mirror with gradient border inspired by Instagram stories.","hi":"Circular mirror with gradient border inspired by Instagram stories."}'::jsonb, 1999, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('profile-picture-mirror', '{"en":"Profile Picture Mirror","hi":"प्रोफ़ाइल पिक्चर मिरर"}'::jsonb, '{"en":"Round mirror with Instagram profile frame border for selfie spots.","hi":"Round mirror with Instagram profile frame border for selfie spots."}'::jsonb, 1799, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('aesthetic-aesthetic-mirror-set', '{"en":"Aesthetic Mirror Set","hi":"एस्थेटिक मिरर सेट"}'::jsonb, '{"en":"Set of 5 small aesthetic mirrors for creating an Instagram-worthy wall.","hi":"Set of 5 small aesthetic mirrors for creating an Instagram-worthy wall."}'::jsonb, 2999, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('trending-audio-mirror', '{"en":"Trending Audio Mirror","hi":"ट्रेंडिंग ऑडियो मिरर"}'::jsonb, '{"en":"LED mirror with music note and waveform design elements.","hi":"LED mirror with music note and waveform design elements."}'::jsonb, 2199, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('collab-mirror-duo', '{"en":"Collab Mirror Duo","hi":"कोलैब मिरर डुओ"}'::jsonb, '{"en":"Pair of matching mirrors perfect for couple and collab content.","hi":"Pair of matching mirrors perfect for couple and collab content."}'::jsonb, 2799, (SELECT id FROM public.categories WHERE slug = 'mirrors-insta'), 'gold', false, true);

-- anime
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('naruto-rasengan-frame', '{"en":"Naruto Rasengan Frame","hi":"नारुतो रसेंगन फ़्रेम"}'::jsonb, '{"en":"Dynamic Naruto artwork with Rasengan energy effect in premium frame.","hi":"Dynamic Naruto artwork with Rasengan energy effect in premium frame."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('gojo-infinity-void-frame', '{"en":"Gojo Infinity Void Frame","hi":"गोजो इनफ़िनिटी वॉइड फ़्रेम"}'::jsonb, '{"en":"Stunning Gojo Satoru with Infinity Void technique in high-quality print.","hi":"Stunning Gojo Satoru with Infinity Void technique in high-quality print."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('luffy-gear-5-frame', '{"en":"Luffy Gear 5 Frame","hi":"लुफ़ी गियर 5 फ़्रेम"}'::jsonb, '{"en":"Epic Luffy Gear 5 transformation artwork with dramatic pose.","hi":"Epic Luffy Gear 5 transformation artwork with dramatic pose."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'anime'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('tanjiro-hinokami-frame', '{"en":"Tanjiro Hinokami Dance Frame","hi":"तांजिरो हिनोकामी फ़्रेम"}'::jsonb, '{"en":"Tanjiro performing Hinokami Kagura with flame breathing effects.","hi":"Tanjiro performing Hinokami Kagura with flame breathing effects."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('jinwoo-shadow-monarch-frame', '{"en":"Jin-Woo Shadow Monarch Frame","hi":"जिन-वू शैडो मोनार्क फ़्रेम"}'::jsonb, '{"en":"Sung Jin-Woo as Shadow Monarch with army of shadows.","hi":"Sung Jin-Woo as Shadow Monarch with army of shadows."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('goku-ultra-instinct-frame', '{"en":"Goku Ultra Instinct Frame","hi":"गोकू अल्ट्रा इंस्टिंक्ट फ़्रेम"}'::jsonb, '{"en":"Goku mastering Ultra Instinct with silver aura energy.","hi":"Goku mastering Ultra Instinct with silver aura energy."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'anime'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('levi-ackerman-frame', '{"en":"Levi Ackerman Frame","hi":"लेवी एकरमन फ़्रेम"}'::jsonb, '{"en":"Captain Levi in action pose with ODM gear from Attack on Titan.","hi":"Captain Levi in action pose with ODM gear from Attack on Titan."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('itachi-sharingan-frame', '{"en":"Itachi Sharingan Frame","hi":"इताची शारिंगन फ़्रेम"}'::jsonb, '{"en":"Itachi Uchiha with Mangekyo Sharingan eye in dramatic dark theme.","hi":"Itachi Uchiha with Mangekyo Sharingan eye in dramatic dark theme."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('sukuna-king-of-curses-frame', '{"en":"Sukuna King of Curses Frame","hi":"सुकुना किंग ऑफ़ कर्सेज़ फ़्रेम"}'::jsonb, '{"en":"Ryomen Sukuna with four arms and cursed energy markings.","hi":"Ryomen Sukuna with four arms and cursed energy markings."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'anime'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('zoro-three-sword-frame', '{"en":"Zoro Three Sword Frame","hi":"ज़ोरो थ्री स्वॉर्ड फ़्रेम"}'::jsonb, '{"en":"Roronoa Zoro in three-sword style attack pose from One Piece.","hi":"Roronoa Zoro in three-sword style attack pose from One Piece."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'anime'), 'gold', false, true);

-- hindu
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('ganesha-utsav-frame', '{"en":"Ganesha Utsav Frame","hi":"गणेश उत्सव फ़्रेम"}'::jsonb, '{"en":"Vibrant Ganesha artwork in festive Utsav colors with ornate border.","hi":"Vibrant Ganesha artwork in festive Utsav colors with ornate border."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('krishna-murli-frame', '{"en":"Krishna Murli Frame","hi":"कृष्ण मुरली फ़्रेम"}'::jsonb, '{"en":"Lord Krishna playing flute under moonlight with peacock feather.","hi":"Lord Krishna playing flute under moonlight with peacock feather."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('ram-darbar-frame', '{"en":"Ram Darbar Frame","hi":"राम दरबार फ़्रेम"}'::jsonb, '{"en":"Complete Ram Darbar with Sita, Lakshman, and Hanuman in royal setting.","hi":"Complete Ram Darbar with Sita, Lakshman, and Hanuman in royal setting."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('shiva-adiyogi-frame', '{"en":"Shiva Adiyogi Frame","hi":"शिव आदियोगी फ़्रेम"}'::jsonb, '{"en":"Meditating Lord Shiva with crescent moon and Himalayan backdrop.","hi":"Meditating Lord Shiva with crescent moon and Himalayan backdrop."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('hanuman-veer-frame', '{"en":"Hanuman Veer Frame","hi":"हनुमान वीर फ़्रेम"}'::jsonb, '{"en":"Powerful Hanuman in flying pose carrying Sanjeevani mountain.","hi":"Powerful Hanuman in flying pose carrying Sanjeevani mountain."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('durga-maa-frame', '{"en":"Durga Maa Frame","hi":"दुर्गा माँ फ़्रेम"}'::jsonb, '{"en":"Goddess Durga in all her glory riding lion with trident.","hi":"Goddess Durga in all her glory riding lion with trident."}'::jsonb, 1049, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('lakshmi-ganesh-diwali-frame', '{"en":"Lakshmi Ganesh Diwali Frame","hi":"लक्ष्मी गणेश दिवाली फ़्रेम"}'::jsonb, '{"en":"Lakshmi and Ganesh together in Diwali celebration theme.","hi":"Lakshmi and Ganesh together in Diwali celebration theme."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('saraswati-veena-frame', '{"en":"Saraswati Veena Frame","hi":"सरस्वती वीणा फ़्रेम"}'::jsonb, '{"en":"Goddess Saraswati playing Veena with white lotus backdrop.","hi":"Goddess Saraswati playing Veena with white lotus backdrop."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('sai-baba-frame', '{"en":"Sai Baba Frame","hi":"साईं बाबा फ़्रेम"}'::jsonb, '{"en":"Serene Shirdi Sai Baba portrait with temple background.","hi":"Serene Shirdi Sai Baba portrait with temple background."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('shivling-nandi-frame', '{"en":"Shivling with Nandi Frame","hi":"शिवलिंग नंदी फ़्रेम"}'::jsonb, '{"en":"Sacred Shivling with Nandi bull and river Ganga flowing.","hi":"Sacred Shivling with Nandi bull and river Ganga flowing."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'hindu'), 'black', false, true);

-- islamic
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('ayatul-kursi-calligraphy-frame', '{"en":"Ayatul Kursi Calligraphy Frame","hi":"आयतुल कुर्सी सुलेख फ़्रेम"}'::jsonb, '{"en":"Elegant Arabic calligraphy of Ayatul Kursi in gold on dark background.","hi":"Elegant Arabic calligraphy of Ayatul Kursi in gold on dark background."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('bismillah-frame', '{"en":"Bismillah Frame","hi":"बिस्मिल्लाह फ़्रेम"}'::jsonb, '{"en":"Beautiful Bismillah calligraphy with geometric Islamic patterns.","hi":"Beautiful Bismillah calligraphy with geometric Islamic patterns."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('makkah-kaaba-frame', '{"en":"Makkah Kaaba Frame","hi":"मक्का काबा फ़्रेम"}'::jsonb, '{"en":"Holy Kaaba at night with golden dome Masjid al-Haram backdrop.","hi":"Holy Kaaba at night with golden dome Masjid al-Haram backdrop."}'::jsonb, 1199, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('madina-masjid-nabawi-frame', '{"en":"Madina Masjid Nabawi Frame","hi":"मदीना मस्जिद नबवी फ़्रेम"}'::jsonb, '{"en":"Prophet's Mosque Masjid Nabawi with green dome in moonlight.","hi":"Prophet's Mosque Masjid Nabawi with green dome in moonlight."}'::jsonb, 1199, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('asma-ul-husna-frame', '{"en":"Asma ul Husna Frame","hi":"अस्मा उल हुस्ना फ़्रेम"}'::jsonb, '{"en":"99 Names of Allah in decorative calligraphy arrangement.","hi":"99 Names of Allah in decorative calligraphy arrangement."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('lailaha-illallah-frame', '{"en":"La Ilaha Illallah Frame","hi":"ला इलाहा इल्लल्लाह फ़्रेम"}'::jsonb, '{"en":"Kalima Tayyiba in bold Arabic script with ornamental border.","hi":"Kalima Tayyiba in bold Arabic script with ornamental border."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('islamic-geometric-art-frame', '{"en":"Islamic Geometric Art Frame","hi":"इस्लामी ज्यामितीय कला फ़्रेम"}'::jsonb, '{"en":"Traditional Islamic geometric patterns in blue and gold mosaic style.","hi":"Traditional Islamic geometric patterns in blue and gold mosaic style."}'::jsonb, 1049, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'black', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('muhammad-pbuh-calligraphy-frame', '{"en":"Muhammad (PBUH) Calligraphy Frame","hi":"मुहम्मद (स.अ.) सुलेख फ़्रेम"}'::jsonb, '{"en":"Respectful Hilye-i-Sharif calligraphy of Prophet Muhammad (PBUH).","hi":"Respectful Hilye-i-Sharif calligraphy of Prophet Muhammad (PBUH)."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('quran-surah-frame', '{"en":"Quran Surah Frame","hi":"क़ुरान सूरह फ़्रेम"}'::jsonb, '{"en":"Surah Al-Fatiha in elegant Thuluth calligraphy script.","hi":"Surah Al-Fatiha in elegant Thuluth calligraphy script."}'::jsonb, 1049, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('dome-mosque-frame', '{"en":"Dome Mosque Frame","hi":"गुंबद मस्जिद फ़्रेम"}'::jsonb, '{"en":"Ornate mosque dome interior view with chandelier and arches.","hi":"Ornate mosque dome interior view with chandelier and arches."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'islamic'), 'gold', false, true);

-- christian
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('sacred-heart-jesus-frame', '{"en":"Sacred Heart of Jesus Frame","hi":"पवित्र हृदय यीशु फ़्रेम"}'::jsonb, '{"en":"Classic Sacred Heart of Jesus portrait with golden halo and divine light.","hi":"Classic Sacred Heart of Jesus portrait with golden halo and divine light."}'::jsonb, 1049, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('virgin-mary-frame', '{"en":"Virgin Mary Frame","hi":"वर्जिन मैरी फ़्रेम"}'::jsonb, '{"en":"Beautiful Virgin Mary portrait with blue veil and praying hands.","hi":"Beautiful Virgin Mary portrait with blue veil and praying hands."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('last-supper-frame', '{"en":"Last Supper Frame","hi":"लास्ट सपर फ़्रेम"}'::jsonb, '{"en":"Leonardo da Vinci's Last Supper in premium art print with classic frame.","hi":"Leonardo da Vinci's Last Supper in premium art print with classic frame."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('good-shepherd-frame', '{"en":"Good Shepherd Frame","hi":"गुड शेफ़र्ड फ़्रेम"}'::jsonb, '{"en":"Jesus as the Good Shepherd with lamb in pastoral setting.","hi":"Jesus as the Good Shepherd with lamb in pastoral setting."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('guardian-angel-frame', '{"en":"Guardian Angel Frame","hi":"गार्डियन एंजेल फ़्रेम"}'::jsonb, '{"en":"Guardian angel watching over children crossing a bridge.","hi":"Guardian angel watching over children crossing a bridge."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('cross-crucifix-frame', '{"en":"Cross Crucifix Frame","hi":"क्रूसीफ़िक्स फ़्रेम"}'::jsonb, '{"en":"Elegant cross design with ornate filigree and divine rays.","hi":"Elegant cross design with ornate filigree and divine rays."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('nativity-scene-frame', '{"en":"Nativity Scene Frame","hi":"नैटिविटी सीन फ़्रेम"}'::jsonb, '{"en":"Christmas nativity scene with baby Jesus, Mary, and Joseph.","hi":"Christmas nativity scene with baby Jesus, Mary, and Joseph."}'::jsonb, 1049, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('praying-hands-frame', '{"en":"Praying Hands Frame","hi":"प्रेइंग हैंड्स फ़्रेम"}'::jsonb, '{"en":"Classic praying hands artwork with rosary and divine light.","hi":"Classic praying hands artwork with rosary and divine light."}'::jsonb, 899, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('st-francis-assisi-frame', '{"en":"St. Francis of Assisi Frame","hi":"सेंट फ़्रांसिस फ़्रेम"}'::jsonb, '{"en":"St. Francis portrait with birds and nature in peaceful setting.","hi":"St. Francis portrait with birds and nature in peaceful setting."}'::jsonb, 949, (SELECT id FROM public.categories WHERE slug = 'christian'), 'wood', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('holy-bible-verse-frame', '{"en":"Holy Bible Verse Frame","hi":"पवित्र बाइबल वर्स फ़्रेम"}'::jsonb, '{"en":"Inspirational Bible verse John 3:16 in calligraphic art.","hi":"Inspirational Bible verse John 3:16 in calligraphic art."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'christian'), 'gold', false, true);

-- landscapes
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('himalayan-sunrise-frame', '{"en":"Himalayan Sunrise Frame","hi":"हिमालय सनराइज़ फ़्रेम"}'::jsonb, '{"en":"Breathtaking sunrise over Himalayan peaks with golden light.","hi":"Breathtaking sunrise over Himalayan peaks with golden light."}'::jsonb, 1199, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('taj-mahal-moonlight-frame', '{"en":"Taj Mahal Moonlight Frame","hi":"ताजमहल मूनलाइट फ़्रेम"}'::jsonb, '{"en":"Iconic Taj Mahal under full moon with reflecting pool.","hi":"Iconic Taj Mahal under full moon with reflecting pool."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('kerala-backwaters-frame', '{"en":"Kerala Backwaters Frame","hi":"केरला बैकवॉटर्स फ़्रेम"}'::jsonb, '{"en":"Serene Kerala houseboat on palm-fringed backwaters at sunset.","hi":"Serene Kerala houseboat on palm-fringed backwaters at sunset."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('rajasthan-desert-frame', '{"en":"Rajasthan Desert Frame","hi":"राजस्थान डेज़र्ट फ़्रेम"}'::jsonb, '{"en":"Camel caravan crossing Thar Desert with sand dunes and sky.","hi":"Camel caravan crossing Thar Desert with sand dunes and sky."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('goa-beach-sunset-frame', '{"en":"Goa Beach Sunset Frame","hi":"गोवा बीच सनसेट फ़्रेम"}'::jsonb, '{"en":"Golden sunset over Goa beach with palm trees silhouette.","hi":"Golden sunset over Goa beach with palm trees silhouette."}'::jsonb, 999, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('valley-of-flowers-frame', '{"en":"Valley of Flowers Frame","hi":"वैली ऑफ़ फ़्लॉवर्स फ़्रेम"}'::jsonb, '{"en":"UNESCO World Heritage Valley of Flowers in full bloom, Uttarakhand.","hi":"UNESCO World Heritage Valley of Flowers in full bloom, Uttarakhand."}'::jsonb, 1199, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('ladakh-pangong-lake-frame', '{"en":"Ladakh Pangong Lake Frame","hi":"लद्दाख पैंगोंग लेक फ़्रेम"}'::jsonb, '{"en":"Crystal blue Pangong Lake with barren mountains backdrop.","hi":"Crystal blue Pangong Lake with barren mountains backdrop."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('varanasi-ghats-frame', '{"en":"Varanasi Ghats Frame","hi":"वाराणसी घाट फ़्रेम"}'::jsonb, '{"en":"Evening Ganga Aarti at Varanasi ghats with oil lamps.","hi":"Evening Ganga Aarti at Varanasi ghats with oil lamps."}'::jsonb, 1149, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('jog-falls-karnataka-frame', '{"en":"Jog Falls Karnataka Frame","hi":"जोग फ़ॉल्स फ़्रेम"}'::jsonb, '{"en":"Majestic Jog Falls in full flow during monsoon season.","hi":"Majestic Jog Falls in full flow during monsoon season."}'::jsonb, 1099, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('kashmir-dal-lake-frame', '{"en":"Kashmir Dal Lake Frame","hi":"कश्मीर डल लेक फ़्रेम"}'::jsonb, '{"en":"Shikara boat on Dal Lake with snow-capped mountains.","hi":"Shikara boat on Dal Lake with snow-capped mountains."}'::jsonb, 1299, (SELECT id FROM public.categories WHERE slug = 'landscapes'), 'gold', false, true);

-- calendars
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('premium-wall-calendar-2026', '{"en":"Premium Wall Calendar 2026","hi":"प्रीमियम वॉल कैलेंडर 2026"}'::jsonb, '{"en":"Large 12-month wall calendar with stunning landscape photos each month.","hi":"Large 12-month wall calendar with stunning landscape photos each month."}'::jsonb, 499, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('desk-calendar-2026', '{"en":"Desk Calendar 2026","hi":"डेस्क कैलेंडर 2026"}'::jsonb, '{"en":"Compact standing desk calendar with weekly planner and beautiful imagery.","hi":"Compact standing desk calendar with weekly planner and beautiful imagery."}'::jsonb, 349, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('hindu-panchang-calendar', '{"en":"Hindu Panchang Calendar","hi":"हिन्दू पंचांग कैलेंडर"}'::jsonb, '{"en":"Traditional Hindu Panchang calendar with festival dates and muhurat.","hi":"Traditional Hindu Panchang calendar with festival dates and muhurat."}'::jsonb, 599, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('islamic-hijri-calendar', '{"en":"Islamic Hijri Calendar","hi":"इस्लामी हिजरी कैलेंडर"}'::jsonb, '{"en":"Islamic Hijri calendar with prayer times and important Islamic dates.","hi":"Islamic Hijri calendar with prayer times and important Islamic dates."}'::jsonb, 549, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('photo-calendar-custom', '{"en":"Custom Photo Calendar","hi":"कस्टम फ़ोटो कैलेंडर"}'::jsonb, '{"en":"Personalized 12-month calendar with YOUR photos — perfect gift.","hi":"Personalized 12-month calendar with YOUR photos — perfect gift."}'::jsonb, 799, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', true, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('motivational-quotes-calendar', '{"en":"Motivational Quotes Calendar","hi":"मोटिवेशनल कोट्स कैलेंडर"}'::jsonb, '{"en":"Daily motivational quotes calendar with inspiring artwork.","hi":"Daily motivational quotes calendar with inspiring artwork."}'::jsonb, 449, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('nature-wildlife-calendar', '{"en":"Nature & Wildlife Calendar","hi":"नेचर वाइल्डलाइफ़ कैलेंडर"}'::jsonb, '{"en":"12 months of stunning wildlife and nature photography.","hi":"12 months of stunning wildlife and nature photography."}'::jsonb, 499, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('bollywood-retro-calendar', '{"en":"Bollywood Retro Calendar","hi":"बॉलीवुड रेट्रो कैलेंडर"}'::jsonb, '{"en":"Classic Bollywood posters calendar with iconic movie art.","hi":"Classic Bollywood posters calendar with iconic movie art."}'::jsonb, 549, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('office-planner-calendar', '{"en":"Office Planner Calendar","hi":"ऑफ़िस प्लैनर कैलेंडर"}'::jsonb, '{"en":"Large office wall planner calendar with monthly and weekly views.","hi":"Large office wall planner calendar with monthly and weekly views."}'::jsonb, 699, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);
INSERT INTO public.products (slug, name, description, base_price, category_id, frame_tone, is_featured, is_active) VALUES ('spiritual-calendar', '{"en":"Spiritual Calendar","hi":"आध्यात्मिक कैलेंडर"}'::jsonb, '{"en":"Multi-faith spiritual calendar with festivals from all religions.","hi":"Multi-faith spiritual calendar with festivals from all religions."}'::jsonb, 599, (SELECT id FROM public.categories WHERE slug = 'calendars'), 'gold', false, true);

-- Step 6: Re-enable triggers
ALTER TABLE public.product_images ENABLE TRIGGER trg_auth_guard;
ALTER TABLE public.products ENABLE TRIGGER trg_auth_guard;
ALTER TABLE public.categories ENABLE TRIGGER trg_auth_guard;
ALTER TABLE public.frame_options ENABLE TRIGGER trg_auth_guard;

DELETE FROM ops.maintenance_flag;
